# _config.yml

# Site settings
title: "Medbase"
description: "Your ultimate questions platform for medical school study and review."
keywords: "Medbase, medical education, MCQ, medical students, healthcare, study platform, medical school, MBBS, medical exams, clinical skills"
baseurl: "" # Leave this blank if deploying at the root level
url: "http://medbase.co.zw" # Update with your actual site URL
image: "https://i.postimg.cc/d3FdX3X7/Logo.png"

# Forms and external links
preorder_form_url: "https://forms.gle/m1btYSLQbxQGVTrb8"

# Author information
author:
  name: "Medbase Team"
  email: "support@medbase.co.zw" # Replace with the correct support email

# Social links (optional)
social:
  twitter: "https://twitter.com/medbase"
  facebook: "https://facebook.com/medbase"
  instagram: "https://instagram.com/medbase"
  linkedin: "https://linkedin.com/company/medbase"

# Custom variables
product_info:
  mission: "To make medical MCQ preparation easier and more accessible for students."
  features:
    - "Comprehensive MCQ library"
    - "Progress tracking"
    - "Real-time feedback on questions"
    - "Cross-platform access on web and mobile"


pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 9

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'


# Deployment settings
# Uncomment and modify for GitHub Pages deployment
# repository: "your_github_username/medbase-landing"
# remote_theme: "minimal-mistakes/minimal-mistakes" # Optional example theme
collections:
  products:
    output: true
    permalink: /product/:name/